# Generated by Django 5.1.6 on 2025-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_delete_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default123', max_length=128),
        ),
    ]
