# Generated by Django 5.1.6 on 2025-04-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
